name: nulla-quas
cot_chain: ReflectBeforeRun
description: |
  Mistral-7B-Instruct -- Sampling --
  Instruction to reflect upon problem with brief pointers
  (characterize, describe typical mistakes, plan)
  before solving it step by step.
tasks: [logiqa, logiqa2, lsat-ar, lsat-rc, lsat-lr]
model: mistralai/Mistral-7B-Instruct-v0.2
modelkwargs:
  max_new_tokens: 1024 
  temperature: 0.3 
  top_k: 100
  top_p: .95 
  trust_remote_code: true
  vllm_kwargs:
    load_format: safetensors
    gpu_memory_utilization: 0.9
    seed: 42
    
