name: nulla-quas
cot_chain: ReflectBeforeRun
description: Add brief description here if manually created.
tasks:
  - logiqa
  - logiqa2
  - lsat-ar
  - lsat-rc
  - lsat-lr
model: mistralai/Mistral-7B-Instruct-v0.2
modelkwargs:
  max_tokens: 960 # Maximum number of tokens to generate per output sequence.
  n: 1 # Number of output sequences to return for the given prompt.
  temperature: 1.0 # Float that controls the randomness of the sampling.
  top_p: 1.0 # Float that controls the cumulative probability of the top tokens to consider.
