name: docker-ci

on:
  workflow_dispatch:

env:
  VLLM_VERSION: 0.4.0.post1
  # harness v4.2.0 does not work with vllm:
  # https://github.com/EleutherAI/lm-evaluation-harness/issues/1600
  # using main branch while waiting for new release
  LM_EVAL_VERSION: main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # https://github.com/jlumbroso/free-disk-space/tree/54081f138730dfa15788a46383842cd2f914a1be#example
      - 
        name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          build-args: |
            VLLM_VERSION=${{ env.VLLM_VERSION }}
            LM_EVAL_VERSION=${{ env.LM_EVAL_VERSION }}
          tags: logikon/cot-eval:latest,logikon/cot-eval:vllm-${{ env.VLLM_VERSION }}_harness-${{ env.LM_EVAL_VERSION }}
